### ISSUE TITLE
升级HA的core到5.0以上版本，通过Aqara Gateway组件接入的都不能控制了

### ISSUE THREAD

**Issue by syxuxiaoliang** [Necroneco/AqaraGateway#1]
最近发现升级HA的core到5.0以上版本，通过Aqara Gateway组件接入的都不能控制了，请问一下，有可能是什么问题？2024.4.3和2024.4.4可以正常控制，只到升级到5.0以上几个版本都不行，点开关按钮，灯不受控，按钮也会自己回到关的状态，只有警戒模式有反应

**Comment by caibinqing** [comment]
有没有日志什么的可以看看? 我这边都还挺正常的

**Comment by syxuxiaoliang** [comment]
现在发现，可能是那个目录里有备份的文件夹，虽然改名了还是在生效，删除后只留一个，又正常了

**Comment by caibinqing** [comment]
好，我想也是，2024.5 没改什么特别的东西。

**Comment by syxuxiaoliang** [comment]
新的版本是不是没集成你对D200锁的修改？升级后有些组件没有了，我用你的文件替换了一下

**Comment by caibinqing** [comment]
嗯，那个提交还没有被合并，原作者可能希望对其他的锁也一样处理。我之前没什么时间处理这个，最近有点空可能会试着去改一下。

**Comment by syxuxiaoliang** [comment]
如果要替换，是替换哪几个文件呢？

**Comment by caibinqing** [comment]
全换掉呗，我都合了
